name: metatensor

on:
  push:
    branches: [main]
  schedule:
    # run at 10:05 every day
    - cron: '5 10 * * *'
  pull_request:
    # Check all PR

jobs:
  check-new-commits:
    runs-on: ubuntu-latest
    outputs:
      n_commits: ${{ steps.check-commits.outputs.n_commits }}
    steps:
      - name: clone metatensor
        uses: actions/checkout@v3
        with:
          repository: lab-cosmo/metatensor

      - id: check-commits
        name: check for recent commits
        run: echo "n_commits=$(git log --oneline --since='24 hours ago' | wc -l)" >> "$GITHUB_OUTPUT"

  build-core-wheels:
    needs: check-new-commits
    # build wheels for new commits on metatensor or this repo
    if: ${{ needs.check-new-commits.outputs.n_commits > 0 || github.event_name == 'pull_request' || github.event_name == 'push' }}

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: x86_64 Linux
            os: ubuntu-latest
            rust-target: x86_64-unknown-linux-gnu
            cibw_arch: x86_64
          - name: x86_64 macOS
            os: macos-latest
            rust-target: x86_64-apple-darwin
            cibw_arch: x86_64
          - name: M1 macOS
            os: macos-latest
            rust-target: aarch64-apple-darwin
            cibw_arch: arm64
          - name: x86_64 Windows
            os: windows-latest
            rust-target: x86_64-pc-windows-msvc
            cibw_arch: AMD64

    steps:
      - name: clone metatensor
        uses: actions/checkout@v3
        with:
          repository: lab-cosmo/metatensor
          fetch-depth: 0

      - name: checkout nightly-wheels
        uses: actions/checkout@v3
        with:
          path: nightly-wheels

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.rust-target }}

      - name: install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: build manylinux with rust docker image
        if: matrix.os == 'ubuntu-latest'
        run: docker build -t rustc-manylinux2014_x86_64 nightly-wheels/rustc-manylinux2014_x86_64

      - name: build metatensor-core wheels
        run: python -m cibuildwheel --output-dir wheelhouse python/metatensor-core
        env:
          CIBW_BUILD: cp310-*
          CIBW_SKIP: "*-musllinux*"
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          CIBW_BUILD_VERBOSITY: 2
          CIBW_MANYLINUX_X86_64_IMAGE: rustc-manylinux2014_x86_64

      - name: upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: |
            wheelhouse/*.whl
            wheelhouse/*.tar.gz

  build-other:
    needs: check-new-commits
    # build wheels for new commits on metatensor or this repo
    if: ${{ needs.check-new-commits.outputs.n_commits > 0 || github.event_name == 'pull_request' || github.event_name == 'push' }}

    runs-on: ubuntu-latest
    name: Other wheels

    steps:
      - name: clone metatensor
        uses: actions/checkout@v3
        with:
          repository: lab-cosmo/metatensor
          fetch-depth: 0

      - name: checkout nightly-wheels
        uses: actions/checkout@v3
        with:
          path: nightly-wheels

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: install dependencies
        run: python -m pip install build

      - name: build sdist and other wheels
        run: |
          python -m build --sdist python/metatensor-core --outdir wheelhouse
          python -m build --sdist python/metatensor-torch --outdir wheelhouse
          python -m build python/metatensor-operations --outdir wheelhouse
          python -m build python/metatensor-learn --outdir wheelhouse
          python -m build . --outdir wheelhouse

      - name: upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: |
            wheelhouse/*.whl
            wheelhouse/*.tar.gz

  update-gh-pages:
    needs: ["build-core-wheels", "build-other"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheels

      - name: create separate directories
        run: |
          ls wheels
          mkdir metatensor-core
          mv wheels/metatensor_core* metatensor-core  # wheel
          mv wheels/metatensor-core* metatensor-core  # sdist

          mkdir metatensor-torch
          mv wheels/metatensor-torch* metatensor-torch  # sdist

          mkdir metatensor-operations
          mv wheels/metatensor_operations* metatensor-operations  # wheel
          mv wheels/metatensor-operations* metatensor-operations  # sdist

          mkdir metatensor-learn
          mv wheels/metatensor_learn* metatensor-learn  # wheel
          mv wheels/metatensor-learn* metatensor-learn  # sdist

          mkdir metatensor
          mv wheels/metatensor* metatensor

      - name: create index files
        run: |
          python create-index.py metatensor-core > metatensor-core/index.html
          python create-index.py metatensor-torch > metatensor-torch/index.html
          python create-index.py metatensor-operations > metatensor-operations/index.html
          python create-index.py metatensor-learn > metatensor-learn/index.html
          python create-index.py metatensor > metatensor/index.html

      - name: deploy metatensor-core to gh-pages
        # only deploy from schedule/push to main branch
        if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./metatensor-core
          destination_dir: metatensor-core

      - name: deploy metatensor-torch to gh-pages
        if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./metatensor-torch
          destination_dir: metatensor-torch

      - name: deploy metatensor-operations to gh-pages
        if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./metatensor-operations
          destination_dir: metatensor-operations

      - name: deploy metatensor-learn to gh-pages
        if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./metatensor-learn
          destination_dir: metatensor-learn

      - name: deploy metatensor to gh-pages
        if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./metatensor
          destination_dir: metatensor
