name: rascaline

on:
  push:
    branches: [main]
  schedule:
    # run at 10:10 every day
    - cron: '10 10 * * *'
  pull_request:
    # Check all PR

jobs:
  check-new-commits:
    runs-on: ubuntu-latest
    outputs:
      n_commits: ${{ steps.check-commits.outputs.n_commits }}
    steps:
      - name: clone rascaline
        uses: actions/checkout@v3
        with:
          repository: luthaf/rascaline

      - id: check-commits
        name: check for recent commits
        run: echo "n_commits=$(git log --oneline --since='24 hours ago' | wc -l)" >> "$GITHUB_OUTPUT"

  build-wheels:
    needs: check-new-commits
    # build wheels for new commits on rascaline or this repo
    if: ${{ needs.check-new-commits.outputs.n_commits > 0 || github.event_name == 'pull_request' || github.event_name == 'push' }}

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: x86_64 Linux
            os: ubuntu-latest
            rust-target: x86_64-unknown-linux-gnu
            cibw_arch: x86_64
            build-extra: true
          - name: x86_64 macOS
            os: macos-latest
            rust-target: x86_64-apple-darwin
            cibw_arch: x86_64
          - name: M1 macOS
            os: macos-latest
            rust-target: aarch64-apple-darwin
            cibw_arch: arm64
          - name: x86_64 Windows
            os: windows-latest
            rust-target: x86_64-pc-windows-msvc
            cibw_arch: AMD64

    steps:
      - name: clone rascaline
        uses: actions/checkout@v3
        with:
          repository: luthaf/rascaline
          fetch-depth: 0

      - name: checkout nightly-wheels
        uses: actions/checkout@v3
        with:
          path: nightly-wheels

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.rust-target }}

      - name: install cibuildwheel
        run: python -m pip install cibuildwheel build

      - name: build manylinux with rust docker image
        if: matrix.os == 'ubuntu-latest'
        run: docker build -t rustc-manylinux2010_x86_64 nightly-wheels/rustc-manylinux2010_x86_64

      - name: build rascaline
        run: python -m cibuildwheel --output-dir wheelhouse .
        env:
          CIBW_BUILD: cp310-*
          CIBW_SKIP: "*-musllinux*"
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          CIBW_BUILD_VERBOSITY: 2
          CIBW_MANYLINUX_X86_64_IMAGE: rustc-manylinux2010_x86_64
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-wheel --ignore-missing-dependencies --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair --exclude libequistore.so -w {dest_dir} {wheel}"

      - name: build sdist
        if: ${{ matrix.build-extra }}
        run: |
          python -m build --sdist . --outdir wheelhouse

      - name: upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: |
            wheelhouse/*.whl
            wheelhouse/*.tar.gz

  update-gh-pages:
    needs: build-wheels
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheels

      - name: create separate directories
        run: |
          ls wheels
          mkdir rascaline
          mv wheels/rascaline* rascaline

      - name: create index files
        run: |
          python create-index.py rascaline > rascaline/index.html

      - name: deploy rascaline to gh-pages
        # only deploy from schedule/push to main branch
        if: ${{ github.event_name == 'schedule' || github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./rascaline
          destination_dir: rascaline
